name: Zip Configs

on:
  push:
    paths:
    - 'configs/**'


jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: configs/ manifest.json
          recursive: true
          dest: configs/configs.zip
